core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .import views
app_name="core"
urlpatterns = [
    path("",views.home,name="home"),
    
    path("contact/",views.contact,name="contact"),
    path("join/",views.member_join,name="join"),
    path("succes_join/",views.success,name="success"),

    path("devotion/",views.devotions,name="devotion"),
    path("gallery/",views.gallery,name="gallery"),
    path("events/",views.events,name="events"),
    path("donate/",views.donations,name="donate"),
    path("search/",views.search,name="search"),
    path("calendar/",views.calendar,name="calendar")

    
]
# path("about/",views.about,name="about"),
#path("join/",views.member_join,name="join")

elcz/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include("core.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "campus ministry"
admin.site.site_title="campus ministry"

core/models.py
from django.db import models

# Create your models here.
class Members(models.Model):
    firstname=models.CharField(max_length=200)
    lastname=models.CharField(max_length=200)
    phonenumber=models.TextField(default="")
    county=models.TextField(default="")
    college=models.TextField(default="")
    def __str__(self):
        return self.firstname +"  "+self.lastname + "  "+ self.college + "  "+ self.phonenumber
    class Meta:
        verbose_name_plural="Members"
    

class WeeklyDevotion(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField(default="")
    new=models.BooleanField(default=True)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural="WeeklyDevotion"

class Gallery(models.Model):
    image=models.ImageField(upload_to="media")
    title=models.CharField(max_length=50)
    description=models.TextField(default="")
    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural="Gallery"

class Events(models.Model):
    date=models.DateField()
    title=models.CharField(max_length=60)
    decription=models.CharField(max_length=60)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural="Events"

class Sermon(models.Model):
    title=models.CharField(max_length=60)
    sermon=models.TextField()
    week=models.IntegerField()

########
#sunday sermon

#######
##questions

##lcms.org

core/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Members,Events,Gallery,WeeklyDevotion,Sermon
from django.contrib import messages
from django.db.models import Q
# Create your views here.
def home(request):
    sermons=Sermon.objects.all()
    return render(request,"core/index.html")

# def about(request):
#     return render(request,"core/about.html")

def contact(request):
    return render(request,"core/contact.html")

def member_join(request):
    if request.method =="POST":
        phonenumber=request.POST.get('phonenumber')
        county=request.POST.get('county')
        firstname=request.POST.get('firstname')
        lastname=request.POST.get('lastname')
        college=request.POST.get("college")
        criterion1 = Q(phonenumber__contains=phonenumber)
        criterion2 = Q(college__contains=college)
        member=Members(phonenumber=phonenumber,county=county,firstname=firstname,lastname=lastname,college= college)
        member_find=Members.objects.filter(criterion1 & criterion2)
        if member_find:
            messages.error(request,"member with the above details already exists")
            return redirect("core:home")
        else:
            member.save()
            messages.success(request,"member added successfully")
            return redirect("core:home")
    return render(request,"core/index.html")
    # return render(request,"core/form.html")

def success(request):
    return render(request,"core/success.html")

def events(request):
    events=Events.objects.all()
    if request.method =="POST":
        query=request.POST.get('search')
        print(query)
        results=Events.objects.filter(Q(title__contains=query))
        if results:
            messages.success(request,"results found")
        else:
            messages.error(request,"results not found")
    return render(request,"core/events.html",locals())
def gallery(request):
    images=Gallery.objects.all()
    return render(request,"core/gallery.html",locals())
    

def devotions(request):
    devotions=WeeklyDevotion.objects.all()
    return render(request,"core/devotion.html",locals())

def donations(request):
    return render(request,"core/donate.html")

def search(request):
    pass
#     query=request.GET['what']
#     results=Events.objects.filter(Q(title__icontains=query))
#     return render(request,"core/search.html",locals())

def calendar(request):
    return render(request,"core/calendar.html")

core/templates/core/calendar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>ELCK | seasons</title>
      {% comment %} favicon {% endcomment %}
      <link rel="apple-touch-icon" sizes="180x180" href="{% static 'core/images/apple-touch-icon.png' %}">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static 'core/images/favicon-32x32.png' %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static 'core/images/favicon-16x16.png' %}">
      <link rel="manifest" href="{% static 'core/images/site.webmanifest' %}">
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
      <!-- responsive-->
      <link rel="stylesheet" href="{% static 'core/css/responsive.css' %}">
      <!-- awesome fontfamily -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rajdhani:300,400,500,600,700" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <style>
      #mform{
         display: none;
      }
      *{
         justify-content: center;
      }
      h4{
         font-size: medium;
         font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
      }
      .card-title {
         color: #262626;
         font-size: 1.5em;
         line-height: normal;
         font-weight: 700;
         margin-bottom: 0.5em;
       }
       
       .small-desc {
         font-size: 1em;
         font-weight: 400;
         line-height: 1.5em;
         color: #452c2c;
       }
       
       .small-desc {
         font-size: 1em;
       }
       
       .go-corner {
         display: flex;
         align-items: center;
         justify-content: center;
         position: absolute;
         width: 2em;
         height: 2em;
         overflow: hidden;
         top: 0;
         right: 0;
         background: linear-gradient(135deg, #6293c8, #384c6c);
         border-radius: 0 4px 0 32px;
       }
       
       .go-arrow {
         margin-top: -4px;
         margin-right: -4px;
         color: white;
         font-family: courier, sans;
       }
       
       .card {
         display: none;
         position: relative;
         max-width: 300px;
         max-height: 320px;
         background-color: #f2f8f9;
         border-radius: 10px;
         padding: 2em 1.2em;
         margin: 12px;
         text-decoration: none;
         z-index: 0;
         overflow: hidden;
         background: linear-gradient(to bottom, #c3e6ec, #a7d1d9);
         font-family: Arial, Helvetica, sans-serif;
       }
       #card{
         display: none;
       }
       
       .card:before {
         content: '';
         position: absolute;
         z-index: -1;
         top: -16px;
         right: -16px;
         background: linear-gradient(135deg, #364a60, #384c6c);
         height: 32px;
         width: 32px;
         border-radius: 32px;
         transform: scale(1);
         transform-origin: 50% 50%;
         transition: transform 0.35s ease-out;
       }
       
       .card:hover:before {
         transform: scale(28);
       }
       
       .card:hover .small-desc {
         transition: all 0.5s ease-out;
         color: rgba(255, 255, 255, 0.8);
       }
       
       .card:hover .card-title {
         transition: all 0.5s ease-out;
         color: #33f561;
       }
       .navbar-toggler-icon{
        outline: none;
       }
       .end{
        position: fixed;
        display: flex;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: rgb(13, 13, 13);
        color: white;
        text-align: center;
        margin-top: 30px;
        height: 100px;
      }
       
   </style>

   <body class="body"> 
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="container-fluid">
           <a class="navbar-brand " href="#">campus ministry</a>
           <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse" id="navbarSupportedContent">
             <ul class="navbar-nav me-auto mb-2 mb-lg-0">
               <li class="nav-item">
                 <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a>
               </li>
               <li class="nav-item">
                 <a class="nav-link" href="{% url 'core:events' %}">Events</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:devotion' %}">Weekly Devotion</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:gallery' %}">Gallery</a>
                </li>
             </ul>
           </div>
         </div>
       </nav>
       <img src="{% static 'core/images/calendar.png' %}" alt="" class="mt-4 ml-4">
      <div class="end bg-dark">
        <div class="col-md-4">
            <a href="{%url 'core:home'%}" class="text-light m-2 p-2">Home</a>
            <a href="{%url 'core:events'%}" class="text-light m-2 p-2">Events</a>
            <a href="{%url 'core:devotion'%}" class="text-light m-2 p-2">Devotions</a>
        </div>
        <div class="col-md-8">
          <ul>
            <li class="text-light">call us: +254.....</li>
            <li class="text-light">Email us at:admin@elckcampus.org</li>
            <li class="text-light">For support :support@elckcampus.org</li>
            <li class="text-light">location: </li>
            <p>© <script>document.write(new Date().getFullYear());</script> All Rights Reserved.</p>
          </ul>
        </div>
      </div>
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <script src="{% static 'core/js/bootstrap.bundle.min.js' %}"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
      <script src="{% static 'core/js/custom.js' %}"></script>
   </body>
</html>

core/templates/core/devotion.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>campus | devotion</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
      <!-- responsive-->
      {% comment %} favicon {% endcomment %}
      <link rel="apple-touch-icon" sizes="180x180" href="{% static 'core/images/apple-touch-icon.png' %}">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static 'core/images/favicon-32x32.png' %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static 'core/images/favicon-16x16.png' %}">
      <link rel="manifest" href="{% static 'core/images/site.webmanifest' %}">
      <link rel="stylesheet" href="{% static 'core/css/responsive.css' %}">
      <!-- awesome fontfamily -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rajdhani:300,400,500,600,700" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
      <style>
      .devotion{
         display:flex;
         justify-content: center;
      }
      body{
         background: url(https://images.unsplash.com/photo-1569153290715-aa8913c6dbae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1625&q=80);
         background-position: center;
         background-repeat: no-repeat;
      }
      .devrow{
         display: flex;
         flex-wrap: wrap;
         margin: 20px;
      }
      .devcard{
         width:300px;
         align-self: normal;
         background-color:Lavender;
         box-shadow:0 0 15px rgb(0, 0, 0);
         flex:1 1 21rem;
         flex-direction: column;
         padding: 20px;
         border-radius: 10px;
         margin-left:30px;
         margin-bottom: 30px;
         align-items: center;
         
      }
      
      .new{
         left:auto;
         background-color: crimson;
         text-align: left;
         border-radius: 5px;
         padding: 5px;
      }
      .mfooter{
         position: sticky;
         justify-content: center;
      }
      </style>
   </head>
   <!-- body -->
   <body class="main-layout inner_page">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static 'core/images/loading.gif' %}" alt="" /></div>
      </div>
      <!-- end loader -->
      <div id="mySidepanel" class="sidepanel">
         <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
         <a  href="{%url 'core:home'%}">Home</a>
         <a href="{%url 'core:devotion'%}" class="active">weekly devotions</a>
         <a href="{%url 'core:events'%}">Events</a>
         <a href="{%url 'core:gallery'%}">Gallery</a>
      </div>
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="head-top">
            <div class="container-fluid">
               <div class="row d_flex">
                  <div class="col-sm-3">
                     <div class="logo">
                     
                     </div>
                  </div>
                  <div class="col-sm-9">
                     <ul class="email text_align_right">
                        <li><a href="Javascript:void(0)"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                        <li><a href="Javascript:void(0)"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                        <li> <button class="openbtn" onclick="openNav()"><img src="{% static 'core/images/menu_btn.png' %}"></button></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header -->
         <div class="devotion">
            <div class="devrow">
               {% for sermon in sermons %}
                  <div class="devcard">
                     <h5 class="text-center">{{sermon.title}}</h5>
                     <p class="fs-20px">{{sermon.sermon}}</p>
                     <hr>
                     <p class="text-center">{{sermon.week}}</p>
                  </div>
               {%empty%} 
               <p class="text-center">No sunday sermon added yet</p>
               {% endfor %}
               
               {% for devotion in devotions %}
                  <div class="devcard">
                     {% if devotion.new %}<span class="new text-light">new</span>{% endif %}
                     <h5 class="text-center">{{devotion.title}}</h5>
                     <p class="fs-20px">{{devotion.description}}</p>
                  </div>
               {%empty%} 
               <p class="text-center">oops we forgot to add some devotions</p>
               {% endfor %}
               
            </div>
         </div>
         <footer>
            <div class="footer">
               <div class="container">
                  <div class="row">
                     <div class="col-md-8 offset-md-2">
                        <h3>Follow Us</h3>
                        <ul class="social_icon text_align_center">
                           <li> <a href="Javascript:void(0)"><i class="fa fa-facebook-f"></i></a></li>
                           <li> <a href="Javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                           <li> <a href="Javascript:void(0)"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                           <li> <a href="Javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                           <li> <a href="Javascript:void(0)"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                        </ul>
                        <div class="conta text_align_center">
                           <ul>
                              <li> <a href="Javascript:void(0)"><img src="{% static 'core/images/call.png' %}" alt="#"/>Call :+254713378817
                                 </a>
                              </li>
                              <li> <a href="Javascript:void(0)"><img src="{% static 'core/images/mall.png' %}" alt="#"/> contact@elckcampus.org
                                 </a>
                              </li>
                           </ul>
                        </div>
                     </div>
                     <div class="col-md-8 offset-md-2">
                        <div class="menu_bottom text_align_center">
                           <ul>
                              <li><a href="{%url 'core:home'%}">Home</a></li>
                              <li><a href="{%url 'core:events'%}">Events</a></li>
                              <li><a href="{%url 'core:devotion'%}">Devotions</a></li>
                              <li><a href="{%url 'core:gallery'%}">gallery</a></li>
                           </ul>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="copyright text_align_center">
                  <div class="container">
                     <div class="row">
                        <div class="col-md-8 offset-md-2">
                           <p>© <script>document.write(new Date().getFullYear());</script> All Rights Reserved.</p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </footer>
     
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="{% static 'core/js/bootstrap.bundle.min.js' %}"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
      <script src="{% static 'core/js/custom.js' %}"></script>
   </body>
</html>

core/templates/core/events.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>elck ministries | events</title>
      <style>
      </style>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
      <!-- responsive-->
      <link rel="stylesheet" href="{% static 'core/css/responsive.css' %}">
      <!-- awesome fontfamily -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rajdhani:300,400,500,600,700" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      {% comment %} favicon {% endcomment %}
      <link rel="apple-touch-icon" sizes="180x180" href="{% static 'core/images/apple-touch-icon.png' %}">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static 'core/images/favicon-32x32.png' %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static 'core/images/favicon-16x16.png' %}">
      <link rel="manifest" href="{% static 'core/images/site.webmanifest' %}">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
      <style>
         .row{
            flex-flow: column-reverse;
            padding-bottom: 100px;
         }
         .end{
            position: fixed;
            display: flex;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: rgb(13, 13, 13);
            color: white;
            text-align: center;
            margin-top: 30px;
            height: 80px;
          }
      </style>
   </head>
   <!-- body -->
   <body class="main-layout inner_page body">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static 'core/images/loading.gif' %}" alt="" /></div>
      </div>
      <!-- end loader -->
      <div id="mySidepanel" class="sidepanel">
         <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
         <a  href="{%url 'core:home'%}">Home</a>
         <a href="{%url 'core:devotion'%}">weekly devotions</a>
         <a href="{%url 'core:events'%}" class="active">Events</a>
         <a href="{%url 'core:gallery'%}">Gallery</a>
      </div>
      <!-- header -->
      <header>
         <!-- header inner -->

                  <div class="col-sm-3">
                     <div class="logo">
                        <a href="{%url 'core:home'%}"><img src="" /></a>
                     </div>
                  </div>
                  <div class="col-sm-9">
                     <ul class="email text_align_right">
                        <li> <button class="openbtn" onclick="openNav()"><img src="{% static 'core/images/menu_btn.png' %}" class="mt-2"></button></li>
                     </ul>
                  </div>
      </header>
      {% if messages %}
         {% for message in messages %}
               <div class="container-fluid p-2 m-3">
                  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="True">&times;</span>
                        </button>
                        {{ message }}
                  </div>
               </div>
         {% endfor %}
      {% endif %}
      <!-- end header -->
      
   {% comment %} cards {% endcomment %}

   <h1 class=" fw-bold text-center">EVENTS AND PROGRAMMES</h1>
   </div>
   <div class="row">
      <section class="main-section container">
         {% for event in events  %}
               <div class="card">
                  <div class="card-body">
                     <h6 class=" text-center" style="font-family:'Mukta', sans-serif;font-size:14px;">TITLE:{{event.title}}</h6>
                     <hr>
                     <p style="font-family:'Lexend', sans-serif;font-size:18px;" class="p-1">{{event.decription}}</p>
                     
                  </div>
                  <hr>
                  
                  <div class="text-center"><i class="fa fa-calendar"></i>&nbsp;&nbsp;{{event.date}}</p></div>
               </div>
         {% endfor %}
      </section>  
      <hr></br>
   </div>
      <!-- footer -->
      <div class="end bg-dark">
         <div class="col-md-4">
             <a href="{%url 'core:home'%}" class="text-light m-2 p-2">Home</a>
             <a href="{%url 'core:events'%}" class="text-light m-2 p-2">Events</a>
             <a href="{%url 'core:devotion'%}" class="text-light m-2 p-2">Devotions</a>
             <a href="{%url 'core:donate'%}" class="text-light m-2 p-2">Donate</a>
         </div>
         <div class="col-md-8">
           <ul>
             <li class="text-light">call us:&nbsp;&nbsp;  +254.....</li>
             <li class="text-light">Email us at: &nbsp; &nbsp; contact@elckcampus.org</li>
             <li class="text-light">location: </li>
             <p>© <script>document.write(new Date().getFullYear());</script></p>
           </ul>
         </div>
      </div>
      <!-- Javascript files-->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
      <script src="{% static 'core/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'core/js/custom.js' %}"></script>
   </body>
</html>

core/templates/core/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="container-fluid p-2 m-3">
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="True">&times;</span>
            </button>
            {{ message }}
        </div>
    </div>
    {% endfor %}
{% endif %}